module.exports = [
  
  {
    title: "Veer-Zaara",
    year: 2004,
    genres: ["Romance", "Drama", "Family"],
    moods: ["emotional", "romantic"],
    description: 
      "Veer-Zaara (2004) is a poignant Yash Chopra romantic drama starring Shah Rukh Khan as an Indian Air Force pilot and Preity Zinta as a Pakistani woman.",
    director: "Yash Chopra",
    cast: ["Shah Rukh Khan", "Preity Zinta", "Amitabh Bachchan", "Manoj Bajpayee", "Hema Malini"],
    imdbRating: 8.9,
    rating: 8.9,
    ratingCount: 96,
    language: "Hindi",
    duration: 192,
    posterUrl: "assets/licensed-image.jpg"

    
  },

  {
    title: "Aashiqui 2",
    year: 2013,
    genres: ["Romance", "Drama", "Musical"],
    moods: ["romantic", "emotional", "intense"],
    description:
      "A fading singer discovers a talented bar singer and helps her rise to fame, but their love story is tested by addiction, insecurity, and sacrifice.",
    director: "Mohit Suri",
    cast: ["Aditya Roy Kapur", "Shraddha Kapoor"],
    imdbRating: 7.0,
    rating: 8.2,
    ratingCount: 96,
    language: "Hindi",
    duration: 134,
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/f/f3/Aashiqui_2_%28Poster%29.jpg",
  },
  {
    title: "Laal Rang",
    year: 2016,
    genres: ["Crime", "Drama", "Thriller"],
    moods: ["dark", "intense", "thought-provoking"],
    description:
      "Set in Haryana, this crime drama follows two friends drawn into an illegal blood trade, where greed, loyalty, and local power collide.",
    director: "Syed Ahmad Afzal",
    cast: ["Randeep Hooda", "Akshay Oberoi", "Pia Bajpai"],
    imdbRating: 7.8,
    rating: 8.1,
    ratingCount: 44,
    language: "Hindi / Haryanvi",
    duration: 147,
    posterUrl: "assets/laal-rang.png",
  },
  {
    title: "Yeh Jawaani Hai Deewani",
    year: 2013,
    genres: ["Romance", "Comedy", "Drama"],
    moods: ["romantic", "feel-good", "nostalgic"],
    description:
      "A shy student and a free-spirited traveller reconnect years after a mountain trek, balancing ambition, friendship, and love.",
    director: "Ayan Mukerji",
    cast: ["Ranbir Kapoor", "Deepika Padukone", "Aditya Roy Kapur"],
    imdbRating: 7.3,
    rating: 8.0,
    ratingCount: 122,
    language: "Hindi",
    duration: 159,
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/1/15/Yeh_jawani_hai_deewani.jpg/250px-Yeh_jawani_hai_deewani.jpg",
  },
  {
    title: "3 Idiots",
    year: 2009,
    genres: ["Comedy", "Drama"],
    moods: ["feel-good", "inspiring", "funny"],
    description:
      "Three engineering students challenge a rigid education system while learning about friendship, passion, and the courage to follow their own path.",
    director: "Rajkumar Hirani",
    cast: ["Aamir Khan", "R. Madhavan", "Sharman Joshi", "Kareena Kapoor"],
    imdbRating: 8.4,
    rating: 9.0,
    ratingCount: 310,
    language: "Hindi",
    duration: 171,
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/3_idiots_poster.jpg/250px-3_idiots_poster.jpg",
  },
  {
    title: "Dangal",
    year: 2016,
    genres: ["Biography", "Drama", "Action"],
    moods: ["inspiring", "emotional", "uplifting"],
    description:
      "A former wrestler trains his daughters to become world-class athletes, challenging social expectations and fighting for national pride.",
    director: "Nitesh Tiwari",
    cast: ["Aamir Khan", "Fatima Sana Shaikh", "Sanya Malhotra", "Sakshi Tanwar"],
    imdbRating: 8.3,
    rating: 8.9,
    ratingCount: 285,
    language: "Hindi / Haryanvi",
    duration: 161,
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/9/99/Dangal_Poster.jpg/250px-Dangal_Poster.jpg",
  },
  {
    title: "Zindagi Na Milegi Dobara",
    year: 2011,
    genres: ["Comedy", "Drama", "Adventure"],
    moods: ["feel-good", "inspiring", "funny"],
    description:
      "Three friends take a road trip across Spain that turns into a journey of adventure, healing, friendship, and choosing life fully.",
    director: "Zoya Akhtar",
    cast: ["Hrithik Roshan", "Abhay Deol", "Farhan Akhtar", "Katrina Kaif"],
    imdbRating: 8.2,
    rating: 8.6,
    ratingCount: 178,
    language: "Hindi",
    duration: 154,
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Zindagi_Na_Milegi_Dobara.jpg/250px-Zindagi_Na_Milegi_Dobara.jpg",
  },
];
