
const path = require("path");
require("dotenv").config({ path: path.join(__dirname, ".env") });
const mongoose = require("mongoose");
const Movie = require("./models/Movie");
const indianMovies = require("./indianMovies");

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/movierecommender";

const movies = [
  {
    title: "Inception",
    year: 2010,
    genres: ["Sci-Fi", "Thriller", "Action"],
    moods: ["mind-bending", "thrilling", "thought-provoking"],
    description:
      "A skilled thief who steals secrets through the use of dream-sharing technology is offered a chance to have his criminal record erased if he can successfully plant an idea into a target's subconscious.",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    imdbRating: 8.8,
    rating: 9.1,
    ratingCount: 245,
    language: "English",
    duration: 148,
    posterUrl: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
  },
  {
    title: "The Shawshank Redemption",
    year: 1994,
    genres: ["Drama"],
    moods: ["inspiring", "emotional", "uplifting"],
    description:
      "Over the course of several years, two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman"],
    imdbRating: 9.3,
    rating: 9.5,
    ratingCount: 312,
    language: "English",
    duration: 142,
    posterUrl: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
  },
  {
    title: "The Dark Knight",
    year: 2008,
    genres: ["Action", "Crime", "Drama"],
    moods: ["thrilling", "dark", "intense"],
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    imdbRating: 9.0,
    rating: 9.2,
    ratingCount: 298,
    language: "English",
    duration: 152,
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
  },
  {
    title: "Interstellar",
    year: 2014,
    genres: ["Sci-Fi", "Drama", "Adventure"],
    moods: ["emotional", "mind-bending", "epic"],
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth becomes increasingly uninhabitable.",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    imdbRating: 8.7,
    rating: 8.9,
    ratingCount: 187,
    language: "English",
    duration: 169,
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  },
  {
    title: "Parasite",
    year: 2019,
    genres: ["Drama", "Thriller", "Comedy"],
    moods: ["dark", "thought-provoking", "intense"],
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    imdbRating: 8.5,
    rating: 8.8,
    ratingCount: 156,
    language: "Korean",
    duration: 132,
    posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  },
  {
    title: "The Lion King",
    year: 1994,
    genres: ["Animation", "Adventure", "Drama"],
    moods: ["feel-good", "emotional", "inspiring", "nostalgic"],
    description:
      "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself. Simba must overcome tragedy and self-doubt to claim his birthright.",
    director: "Roger Allers",
    cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
    imdbRating: 8.5,
    rating: 8.7,
    ratingCount: 203,
    language: "English",
    duration: 88,
    posterUrl: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    genres: ["Crime", "Drama", "Thriller"],
    moods: ["dark", "thrilling", "edgy"],
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    imdbRating: 8.9,
    rating: 8.8,
    ratingCount: 267,
    language: "English",
    duration: 154,
    posterUrl: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
  },
  {
    title: "Avengers: Endgame",
    year: 2019,
    genres: ["Action", "Adventure", "Sci-Fi"],
    moods: ["epic", "emotional", "feel-good", "thrilling"],
    description:
      "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos's actions and restore balance to the universe.",
    director: "Anthony Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    imdbRating: 8.4,
    rating: 8.6,
    ratingCount: 334,
    language: "English",
    duration: 181,
    posterUrl: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
  },
  {
    title: "The Pursuit of Happyness",
    year: 2006,
    genres: ["Drama", "Biography"],
    moods: ["inspiring", "emotional", "uplifting"],
    description:
      "Based on the true story of Chris Gardner, a struggling salesman who takes custody of his son as he's on the verge of becoming homeless, while pursuing a career in the stock market.",
    director: "Gabriele Muccino",
    cast: ["Will Smith", "Jaden Smith"],
    imdbRating: 8.0,
    rating: 8.3,
    ratingCount: 189,
    language: "English",
    duration: 117,
    posterUrl: "https://image.tmdb.org/t/p/w500/lBYOKAMcxIvuk9s9hMuecB9dPBV.jpg",
  },
  {
    title: "Get Out",
    year: 2017,
    genres: ["Horror", "Thriller", "Mystery"],
    moods: ["terrifying", "dark", "thought-provoking"],
    description:
      "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness about their reception of him eventually reaches a boiling point.",
    director: "Jordan Peele",
    cast: ["Daniel Kaluuya", "Allison Williams"],
    imdbRating: 7.7,
    rating: 8.0,
    ratingCount: 143,
    language: "English",
    duration: 104,
    posterUrl: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
  },
  {
    title: "Coco",
    year: 2017,
    genres: ["Animation", "Adventure", "Family"],
    moods: ["feel-good", "emotional", "uplifting", "nostalgic"],
    description:
      "Aspiring musician Miguel, confronted with his family's ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    director: "Lee Unkrich",
    cast: ["Anthony Gonzalez", "Gael García Bernal"],
    imdbRating: 8.4,
    rating: 8.6,
    ratingCount: 211,
    language: "English",
    duration: 105,
    posterUrl: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
  },
  {
    title: "Joker",
    year: 2019,
    genres: ["Crime", "Drama", "Thriller"],
    moods: ["dark", "intense", "thought-provoking"],
    description:
      "A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain — Arthur Fleck, the Joker.",
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro"],
    imdbRating: 8.4,
    rating: 8.5,
    ratingCount: 278,
    language: "English",
    duration: 122,
    posterUrl: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
  },
  {
    title: "Spirited Away",
    year: 2001,
    genres: ["Animation", "Adventure", "Fantasy"],
    moods: ["feel-good", "magical", "nostalgic"],
    description:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    director: "Hayao Miyazaki",
    cast: ["Daveigh Chase", "Suzanne Pleshette"],
    imdbRating: 8.6,
    rating: 8.8,
    ratingCount: 167,
    language: "Japanese",
    duration: 125,
    posterUrl: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
  },
  {
    title: "La La Land",
    year: 2016,
    genres: ["Musical", "Romance", "Drama"],
    moods: ["romantic", "feel-good", "emotional"],
    description:
      "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone"],
    imdbRating: 8.0,
    rating: 8.2,
    ratingCount: 198,
    language: "English",
    duration: 128,
    posterUrl: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
  },
  {
    title: "Forrest Gump",
    year: 1994,
    genres: ["Drama", "Romance", "Comedy"],
    moods: ["feel-good", "inspiring", "nostalgic", "emotional"],
    description:
      "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright"],
    imdbRating: 8.8,
    rating: 9.0,
    ratingCount: 289,
    language: "English",
    duration: 142,
    posterUrl: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
  },
  {
    title: "The Matrix",
    year: 1999,
    genres: ["Sci-Fi", "Action"],
    moods: ["mind-bending", "thrilling", "epic"],
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    director: "Lana Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    imdbRating: 8.7,
    rating: 8.9,
    ratingCount: 256,
    language: "English",
    duration: 136,
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
  },
  {
    title: "Titanic",
    year: 1997,
    genres: ["Romance", "Drama", "History"],
    moods: ["romantic", "emotional", "epic"],
    description:
      "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    director: "James Cameron",
    cast: ["Leonardo DiCaprio", "Kate Winslet"],
    imdbRating: 7.9,
    rating: 8.1,
    ratingCount: 234,
    language: "English",
    duration: 194,
    posterUrl: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
  },
  {
    title: "Dune",
    year: 2021,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    moods: ["epic", "thought-provoking", "mind-bending"],
    description:
      "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset in the galaxy.",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya"],
    imdbRating: 8.0,
    rating: 8.3,
    ratingCount: 172,
    language: "English",
    duration: 155,
    posterUrl: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
  },
  {
    title: "A Beautiful Mind",
    year: 2001,
    genres: ["Drama", "Biography"],
    moods: ["inspiring", "emotional", "thought-provoking"],
    description:
      "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.",
    director: "Ron Howard",
    cast: ["Russell Crowe", "Jennifer Connelly"],
    imdbRating: 8.2,
    rating: 8.4,
    ratingCount: 178,
    language: "English",
    duration: 135,
    posterUrl: "https://image.tmdb.org/t/p/w500/rEIg5yJdNOt9fmX4P8gU9LeNoTQ.jpg",
  },
  {
    title: "Everything Everywhere All at Once",
    year: 2022,
    genres: ["Sci-Fi", "Action", "Comedy"],
    moods: ["mind-bending", "feel-good", "emotional"],
    description:
      "A middle-aged Chinese immigrant is swept up in an insane adventure in which she alone can save existence by exploring other universes connecting with the lives she could have led.",
    director: "Daniel Kwan",
    cast: ["Michelle Yeoh", "Ke Huy Quan", "Jamie Lee Curtis"],
    imdbRating: 7.8,
    rating: 8.5,
    ratingCount: 144,
    language: "English",
    duration: 139,
    posterUrl: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
  },
  {
    title: "Home Alone",
    year: 1990,
    genres: ["Comedy", "Family"],
    moods: ["feel-good", "funny", "nostalgic"],
    description:
      "An 8-year-old troublemaker must protect his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation.",
    director: "Chris Columbus",
    cast: ["Macaulay Culkin", "Joe Pesci", "Daniel Stern"],
    imdbRating: 7.7,
    rating: 8.0,
    ratingCount: 221,
    language: "English",
    duration: 103,
    posterUrl: "https://image.tmdb.org/t/p/w500/onTSipZ8R3bliBdKfPtsDuHTdlL.jpg",
  },
  {
    title: "Whiplash",
    year: 2014,
    genres: ["Drama", "Music"],
    moods: ["intense", "inspiring", "thrilling"],
    description:
      "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons"],
    imdbRating: 8.5,
    rating: 8.7,
    ratingCount: 163,
    language: "English",
    duration: 107,
    posterUrl: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
  },
  {
    title: "Midsommar",
    year: 2019,
    genres: ["Horror", "Mystery", "Drama"],
    moods: ["terrifying", "dark", "intense"],
    description:
      "A couple travels to Northern Europe to visit a rural hometown's midsummer festival. What begins as an idyllic retreat quickly devolves into a violent competition.",
    director: "Ari Aster",
    cast: ["Florence Pugh", "Jack Reynor"],
    imdbRating: 7.1,
    rating: 7.4,
    ratingCount: 118,
    language: "English",
    duration: 148,
    posterUrl: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
  },
  {
    title: "The Grand Budapest Hotel",
    year: 2014,
    genres: ["Comedy", "Drama", "Adventure"],
    moods: ["funny", "feel-good", "quirky"],
    description:
      "A writer encounters the owner of an aging European hotel between the two world wars, who tells him of his early years serving as a lobby boy in the hotel's glorious heyday.",
    director: "Wes Anderson",
    cast: ["Ralph Fiennes", "Tony Revolori"],
    imdbRating: 8.1,
    rating: 8.3,
    ratingCount: 145,
    language: "English",
    duration: 99,
    posterUrl: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
  },
  {
    title: "Gladiator",
    year: 2000,
    genres: ["Action", "Adventure", "Drama"],
    moods: ["epic", "inspiring", "thrilling"],
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    director: "Ridley Scott",
    cast: ["Russell Crowe", "Joaquin Phoenix"],
    imdbRating: 8.5,
    rating: 8.7,
    ratingCount: 229,
    language: "English",
    duration: 155,
    posterUrl: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
  },
  {
    title: "Her",
    year: 2013,
    genres: ["Romance", "Sci-Fi", "Drama"],
    moods: ["emotional", "thought-provoking", "romantic"],
    description:
      "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
    director: "Spike Jonze",
    cast: ["Joaquin Phoenix", "Scarlett Johansson"],
    imdbRating: 8.0,
    rating: 8.2,
    ratingCount: 134,
    language: "English",
    duration: 126,
    posterUrl: "https://image.tmdb.org/t/p/w500/lEIaL12hSkqqe83kgADkbUqEnvk.jpg",
  },
  {
    title: "Black Panther",
    year: 2018,
    genres: ["Action", "Adventure", "Sci-Fi"],
    moods: ["epic", "inspiring", "feel-good"],
    description:
      "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    director: "Ryan Coogler",
    cast: ["Chadwick Boseman", "Michael B. Jordan"],
    imdbRating: 7.3,
    rating: 7.8,
    ratingCount: 267,
    language: "English",
    duration: 134,
    posterUrl: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
  },
  {
    title: "Schindler's List",
    year: 1993,
    genres: ["Drama", "History", "Biography"],
    moods: ["emotional", "inspiring", "dark"],
    description:
      "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    director: "Steven Spielberg",
    cast: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"],
    imdbRating: 9.0,
    rating: 9.2,
    ratingCount: 201,
    language: "English",
    duration: 195,
    posterUrl: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
  },
  {
    title: "Inside Out",
    year: 2015,
    genres: ["Animation", "Family", "Comedy"],
    moods: ["feel-good", "emotional", "inspiring", "funny"],
    description:
      "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions — Joy, Fear, Anger, Disgust and Sadness — conflict on how best to navigate a new city, house, and school.",
    director: "Pete Docter",
    cast: ["Amy Poehler", "Mindy Kaling", "Phyllis Smith"],
    imdbRating: 8.2,
    rating: 8.5,
    ratingCount: 213,
    language: "English",
    duration: 95,
    posterUrl: "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
  },

  {
    title: "No Country for Old Men",
    year: 2007,
    genres: ["Crime", "Drama", "Thriller"],
    moods: ["dark", "intense", "thrilling"],
    description:
      "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and finds two million dollars and a wounded man.",
    director: "Joel Coen",
    cast: ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin"],
    imdbRating: 8.2,
    rating: 8.4,
    ratingCount: 156,
    language: "English",
    duration: 122,
    posterUrl: "https://image.tmdb.org/t/p/w500/7d7RFBhnSMd9jhcOwmYkkcr7oFg.jpg",
  },
  ...indianMovies,
];

async function seedDatabase() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    await Movie.deleteMany({});
    console.log("🗑️  Cleared existing movies");

    // Ensure MongoDB has the latest schema indexes before inserting seed data.
    await Movie.syncIndexes();

    // Insert seed data
    const inserted = await Movie.insertMany(movies);
    console.log(`🎬 Inserted ${inserted.length} movies successfully`);

    await mongoose.disconnect();
    console.log("✅ Database seeded. You can now run: node server.js");
    process.exit(0);
  } catch (err) {
    console.error("❌ Seeding failed:", err.message);
    process.exit(1);
  }
}

seedDatabase();
